name: 'CI/CD'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies  # 新增的关键步骤
      run: npm install

    - name: Run Linter
      run: |
        find ./giftlink-backend -name app.js -exec npx eslint {} +
        find ./giftlink-backend -name authRoutes.js -exec npx eslint {} +
        find ./giftlink-backend -name giftRoutes.js -exec npx eslint {} +
        find ./giftlink-backend -name searchRoutes.js -exec npx eslint {} +
        echo "Linted all the js files successfully"


  client_build:
      name: Build client
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run build
        run: |
          cd giftlink-frontend
          npm install
          npm run build
          echo "Client-side build successfully"
