name: 'CI/CD'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_js:
      name: Lint JavaScript Files
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install ESLint
        run: npm install eslint --global

      # - name: Install Project Dependencies
      #   run: npm install

      # - name: Verify Installed Dependencies
      #   run: |
      #     npm list globals
      #     npm list eslint

      - name: Run Linter
        run: |
          # This command finds all JavaScript files recursively and runs ESlint on them
          find ./giftlink-backend -name app.js -exec eslint {} +
          find ./giftlink-backend -name authRoutes.js -exec eslint {} +
          find ./giftlink-backend -name giftRoutes.js -exec eslint {} +
          find ./giftlink-backend -name searchRoutes.js -exec eslint {} +
          echo "Linted all the js files successfully"

  client_build:
      name: Build client
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run build
        run: |
          cd giftlink-frontend
          npm install
          npm run build
          echo "Client-side build successfully"
